((topmost-intro <0,0>))
((defun-block-intro <1,0>))
((inlambda) (defun-block-intro <1,4>))
((inlambda) (inline-close <2,4>))
((arglist-cont-nonempty <3,4> <3,15>) (arglist-cont-nonempty <3,4> <3,22>) (arglist-cont-nonempty <3,4> <3,28>) (comment-intro))
((arglist-cont-nonempty <4,4> <4,15>) (arglist-cont-nonempty <4,4> <4,22>) (arglist-cont-nonempty <4,4> <4,28>))
((defun-close <6,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>) (comment-intro))
((topmost-intro <3,0>) (comment-intro))
((topmost-intro <4,0>) (comment-intro))
