((topmost-intro <0,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((member-init-intro <1,4>))
((inclass <3,0>) (inline-open))
((inclass <4,0>) (topmost-intro <1,0>))
((class-close <5,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((member-init-intro <1,4>))
((inclass <3,0>) (inline-open))
((inclass <4,0>) (topmost-intro <1,0>))
((class-close <5,0>))
