((topmost-intro <0,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((class-close <2,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((topmost-intro-cont <1,0>))
((defun-open <2,0>))
((defun-block-intro <1,0>))
((arglist-cont-nonempty <1,4> <1,8>) (brace-list-intro <1,4>))
((arglist-cont-nonempty <2,4> <2,8>) (brace-list-close <2,4>))
((arglist-close <3,4> <3,8>))
((statement <4,4>))
((arglist-cont-nonempty <1,4> <1,8>) (brace-list-intro <1,4>))
((arglist-cont-nonempty <2,4> <2,8>) (brace-list-close <2,4>))
((statement <3,4>))
((brace-list-intro <1,4>))
((brace-list-close <2,4>))
((defun-close <11,0>))
