((topmost-intro <0,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((brace-list-open <1,4>))
((brace-list-intro <1,4>))
((brace-entry-open <1,8>))
((brace-list-entry <1,9>))
((brace-list-close <2,8>))
((brace-list-entry <3,8>))
((brace-entry-open <4,8>))
((brace-list-intro <1,8>))
((brace-list-entry <1,12>))
((brace-list-close <3,8>))
((brace-list-close <10,4>))
((inclass <13,0>) (topmost-intro <1,0>))
((topmost-intro-cont <1,4>))
((brace-list-intro <1,8>))
((brace-entry-open <1,12>))
((brace-list-entry <1,13>))
((brace-list-close <2,12>))
((brace-list-close <5,8>))
((inclass <20,0>) (topmost-intro <1,0>))
((inclass <21,0>) (inline-open))
((defun-block-intro <1,4>))
((block-open) (statement <1,8>))
((statement-block-intro <1,8>))
((statement-cont <1,12>))
((block-close <3,8>))
((statement <4,8>))
((statement-cont <1,8>))
((brace-list-intro <1,12>))
((brace-list-entry <1,16>))
((brace-list-close <3,12>))
((inline-close <11,4>))
((class-close <33,0>))
