((topmost-intro <0,0>))
((brace-list-intro <1,0>))
((brace-list-entry <1,4>))
((brace-list-entry <2,4>))
((brace-list-close <4,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((brace-list-intro <1,0>) (brace-list-entry <1,14>))
((brace-list-intro <2,0>) (brace-list-entry <2,14>))
((brace-list-close <3,0>))
