((topmost-intro <0,0>))
((defun-block-intro <1,0>))
((arglist-cont-nonempty <1,4> <1,6>) (brace-list-intro <1,4>))
((brace-entry-open <1,12>))
((brace-entry-open <1,12>))
((arglist-cont-nonempty <4,4> <4,6>) (brace-list-close <4,4>))
((statement <5,4>))
((arglist-cont-nonempty <1,4> <1,8>) (arglist-cont-nonempty <1,4> <1,27>) (brace-list-intro <1,4>))
((brace-entry-open <1,16>))
((brace-entry-open <1,16>))
((arglist-cont-nonempty <4,4> <4,8>) (arglist-cont-nonempty <4,4> <4,27>) (brace-list-close <4,4>))
((statement-block-intro <5,4>))
((statement-block-intro <1,8>))
((block-close <2,8>))
((block-close <8,4>))
((statement <9,4>))
((statement <10,4>))
((arglist-cont-nonempty <1,4> <1,6>) (brace-list-intro <1,4>))
((brace-entry-open <1,12>))
((brace-entry-open <1,12>))
((arglist-cont-nonempty <4,4> <4,6>) (brace-list-close <4,4>))
((statement <5,4>))
((arglist-cont-nonempty <1,4> <1,8>) (arglist-cont-nonempty <1,4> <1,27>) (brace-list-intro <1,4>))
((brace-entry-open <1,16>))
((brace-entry-open <1,16>))
((arglist-cont-nonempty <4,4> <4,8>) (arglist-cont-nonempty <4,4> <4,27>) (brace-list-close <4,4>))
((statement-block-intro <5,4>))
((statement-block-intro <1,8>))
((block-close <2,8>))
((block-close <8,4>))
((defun-close <30,0>))
