((topmost-intro <0,0>))
((inclass <1,0>) (access-label <1,0>))
((inclass <2,0>) (topmost-intro <2,0>))
((brace-list-intro <1,4>))
((brace-list-entry <1,8>))
((brace-list-entry <1,8>))
((brace-list-close <4,4>))
((class-close <7,0>))
