((topmost-intro <0,0>))
((member-init-intro <1,0>))
((member-init-cont <1,6>))
((member-init-cont <2,6>))
((defun-open <4,0>))
((defun-close <1,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((member-init-intro <1,0>))
((member-init-cont <1,6>))
((member-init-cont <2,6>))
((defun-open <4,0>))
((defun-close <1,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((member-init-intro <1,0>))
((member-init-cont <1,6>))
((member-init-cont <2,6>))
((defun-open <4,0>))
((defun-close <1,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((member-init-intro <1,0>))
((member-init-cont <1,6>))
((member-init-cont <2,6>))
((defun-open <4,0>))
((defun-close <1,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>) (comment-intro))
((topmost-intro <3,0>) (comment-intro))
((topmost-intro <4,0>) (comment-intro))
((topmost-intro <5,0>) (comment-intro))
