((topmost-intro <0,0>) (cpp-macro))
((topmost-intro <1,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((defun-block-intro <1,4>))
((inline-close <2,4>))
((inclass <4,0>) (topmost-intro <1,0>))
((defun-block-intro <1,4>))
((inline-close <2,4>))
((inclass <7,0>) (topmost-intro <1,0>))
((defun-block-intro <1,4>))
((inline-close <2,4>))
((inclass <10,0>) (topmost-intro <1,0>))
((defun-block-intro <1,4>))
((inline-close <2,4>))
((inclass <13,0>) (topmost-intro <1,0>))
((defun-block-intro <1,4>))
((inline-close <2,4>))
((class-close <16,0>))
