((topmost-intro <0,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((arglist-cont-nonempty <1,4> <1,10>))
((statement-cont <2,4>))
((statement <3,4>))
((class-open <1,4>))
((inclass <1,4>) (topmost-intro <1,0>))
((class-close <3,4>))
((defun-close <8,0>))
((topmost-intro <1,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((arglist-cont-nonempty <1,4> <1,10>))
((statement-cont <2,4>))
((statement <3,4>))
((inclass <1,4>) (topmost-intro <1,0>))
((class-close <2,4>))
((defun-close <7,0>))
((topmost-intro <1,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((arglist-cont-nonempty <1,4> <1,10>))
((statement-cont <2,4>))
((statement <3,4>))
((inexpr-class) (class-open <1,4>))
((inclass <1,8>) (topmost-intro <1,0>))
((inexpr-class) (class-close <3,4>))
((defun-close <8,0>))
((topmost-intro <1,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((arglist-cont-nonempty <1,4> <1,10>))
((statement-cont <2,4>))
((statement <3,4>))
((inexpr-class) (inclass <1,4>) (topmost-intro <1,0>))
((inexpr-class) (class-close <2,4>))
((defun-close <7,0>))
((topmost-intro <1,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((arglist-cont-nonempty <1,4> <1,10>))
((statement-cont <2,4>))
((statement <3,4>))
((defun-open <1,4>))
((defun-block-intro <1,4>))
((defun-close <2,4>))
((statement <4,4>))
((arglist-cont-nonempty <1,4> <1,7>))
((substatement-open <2,4>))
((statement-block-intro <1,8>))
((block-close <2,8>))
((statement <5,4>))
((substatement-open <1,4>))
((statement-block-intro <1,8>))
((block-close <2,8>))
((defun-close <17,0>))
((topmost-intro <1,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((arglist-cont-nonempty <1,4> <1,10>))
((statement-cont <2,4>))
((statement <3,4>))
((defun-block-intro <1,4>))
((defun-close <2,4>))
((statement <3,4>))
((arglist-cont-nonempty <1,4> <1,7>))
((statement-block-intro <2,4>))
((block-close <3,4>))
((statement <4,4>))
((statement-block-intro <1,4>))
((block-close <2,4>))
((defun-close <14,0>))
((topmost-intro <1,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((arglist-cont-nonempty <1,4> <1,10>))
((statement-cont <2,4>))
((statement <3,4>))
((inlambda) (inline-open <1,4>))
((defun-block-intro <1,4>))
((inline-close <2,4>))
((defun-close <8,0>))
((topmost-intro <1,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((arglist-cont-nonempty <1,4> <1,10>))
((statement-cont <2,4>))
((statement <3,4>))
((inlambda) (defun-block-intro <1,4>))
((inlambda) (inline-close <2,4>))
((defun-close <7,0>))
