((topmost-intro <0,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((block-open) (statement <1,4>))
((statement-block-intro <1,4>))
((brace-list-intro <1,8>))
((brace-list-entry <1,12>))
((brace-list-entry <1,12>))
((brace-list-close <4,8>))
((block-close <6,4>))
((defun-close <9,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((brace-list-intro <1,0>))
((brace-list-entry <1,4>))
((brace-list-entry <1,4>))
