((topmost-intro <0,0>))
((knr-argdecl-intro <1,0>))
((knr-argdecl <1,4>))
((defun-open <3,0>))
((defun-block-intro <1,0>))
((defun-close <2,0>))
((topmost-intro <1,0>) (comment-intro))
((topmost-intro <2,0>))
((knr-argdecl-intro <1,0>))
((topmost-intro <1,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((defun-close <2,0>))
