((topmost-intro <0,0>))
((topmost-intro <1,0>))
((topmost-intro <1,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((inlambda) (inline-open <1,4>))
((defun-block-intro <1,4>))
((inline-close <2,4>))
((defun-close <5,0>))
