((topmost-intro <0,0>) (cpp-macro))
((topmost-intro <1,0>) (cpp-macro))
((topmost-intro <2,0>))
((topmost-intro <3,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((statement <1,4>))
((statement <1,4>))
((statement <2,4>))
((inlambda) (defun-block-intro <1,4>))
((inlambda) (inline-close <2,4>))
((statement <3,4>))
((defun-close <8,0>))
