((topmost-intro <0,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((inlambda) (defun-block-intro <1,4>))
((statement <1,22>))
((inexpr-statement) (statement-block-intro <1,22>))
((inexpr-statement) (block-close <2,22>))
((inlambda) (inline-close <5,4>))
((statement <6,4>))
((inlambda) (lambda-intro-cont <1,4>))
((arglist-cont-nonempty <1,18> <1,18>))
((inlambda) (defun-block-intro <3,4>))
((statement <1,18>))
((inexpr-statement) (block-open <1,18>))
((inlambda) (inline-close <6,4>))
((statement <7,4>))
((arglist-cont-nonempty <1,4> <1,8>) (arglist-cont-nonempty <1,4> <1,21>))
((inlambda) (defun-block-intro <2,4>))
((statement <3,4>))
((inlambda) (lambda-intro-cont <1,4>))
((arglist-cont-nonempty <1,18> <1,18>))
((inlambda) (inline-open <3,4>))
((defun-block-intro <1,14>) (statement <1,14>))
((inexpr-statement) (block-open <1,18>))
((statement <6,4>))
((arglist-intro <1,4> <1,27>))
((arglist-cont <1,8>))
((defun-block-intro <1,8>))
((inline-close <2,8>))
((defun-close <28,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>) (comment-intro))
((topmost-intro <3,0>) (comment-intro))
((topmost-intro <4,0>) (comment-intro))
