((topmost-intro <0,0>) (cpp-macro))
((cpp-define-intro <1,0>) (comment-intro))
((c <1,4>))
((c <2,4>))
((cpp-define-intro) (statement <4,0>))
((statement <1,4>) (comment-intro))
((c <1,4>))
((c <2,4>))
((statement <4,4>))
