((topmost-intro <0,0>) (cpp-macro))
((topmost-intro <1,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((topmost-intro <1,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((defun-close <2,0>))
((topmost-intro <1,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((stream-op <1,4>))
((statement <2,4>))
((defun-close <4,0>))
